# Generated by Django 3.1 on 2020-09-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctms', '0002_auto_20200901_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographer',
            name='Profile',
            field=models.ImageField(height_field=1080, upload_to='static/profile_pic', width_field=1080),
        ),
    ]
