# Generated by Django 3.1 on 2020-09-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctms', '0003_auto_20200901_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographer',
            name='Profile',
            field=models.ImageField(upload_to='static/profile_pic'),
        ),
    ]
