# Generated by Django 3.1 on 2020-09-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctms', '0004_auto_20200901_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
