# Generated by Django 3.1 on 2020-09-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctms', '0006_auto_20200901_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
