# Generated by Django 3.1 on 2020-09-04 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctms', '0008_auto_20200902_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='media/backgroungimages/')),
                ('Page', models.CharField(choices=[('i', 'index'), ('s', 'single'), ('a', 'about'), ('c', 'contact')], max_length=1)),
                ('desc', models.CharField(max_length=100)),
            ],
        ),
    ]
