# Generated by Django 3.1 on 2020-09-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctms', '0010_auto_20200921_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='category',
            field=models.CharField(max_length=50),
        ),
    ]
