# Generated by Django 3.1 on 2020-09-21 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ctms', '0011_auto_20200921_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctms.categories'),
        ),
    ]
