# Generated by Django 3.1 on 2020-09-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctms', '0012_auto_20200921_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
