# Generated by Django 3.1 on 2020-09-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctms', '0013_auto_20200921_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
